#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ -d "./KukaApp/node_modules" ]
then
  echo "Developing KukaApp so running Code Style Checks"
  pushd ./KukaApp
  npx lint-staged
  popd
fi

if [ -d "./functions/node_modules" ]
then
  echo "Developing functions so running Code Style Checks"
  pushd ./functions
  npx lint-staged
  popd
fi

if [ -d "./web/node_modules" ]
then
  echo "Developing web so running Code Style Checks"
  pushd ./web
  npx lint-staged
  popd
fi
